-- smart_money_13f: la tabla que escribe app/api/cron/13f-refresh y que faltaba en Cloud SQL.
--
-- En Supabase se creó a mano (no hay DDL en ningún repo), y 001_schema.sql se sacó sin ella:
-- en producción el cron 13f-refresh fallaba al escribir. Columnas copiadas de la definición
-- que publica la API de Supabase; la unicidad es la que usa el cron en su on_conflict.
--
-- Aditiva e idempotente: se puede aplicar dos veces sin error y no toca nada existente.
--   psql "$DATABASE_URL" -f sql/gcp/004_smart_money_13f.sql

create table if not exists public.smart_money_13f (
  id               bigint generated by default as identity primary key,
  fund_cik         text   not null,
  fund_name        text,
  filing_date      date   not null,
  ticker           text   not null,
  shares_held      bigint,
  delta_vs_prior_q bigint,
  action           text,
  market_value_usd numeric,
  constraint smart_money_13f_fund_filing_ticker_key unique (fund_cik, filing_date, ticker)
);

-- Mismo trato que el resto de tablas de datos compartidos: la lee el servidor, no el navegador.
-- 003_rol_app.sql da permisos por defecto a las tablas nuevas, pero solo si esta se crea con el
-- mismo rol que aplicó 003. Se concede explícito para no depender de eso.
do $$
begin
  if exists (select 1 from pg_roles where rolname = 'scora_app') then
    grant select, insert, update, delete on public.smart_money_13f to scora_app;
  end if;
end $$;
