// Historical backtest summary — generated by research/backtest.mjs (point-in-time,
// free data: SEC EDGAR + FMP + FRED). Committed as a static snapshot; re-run the
// research pipeline to refresh. The LIVE record (sl_track_summary) is separate and
// accumulates forward from the monthly cron.

export interface BacktestSummary {
  period: string;
  universe: number;
  rebalances: number;
  nameMonths: number;
  buyThreshold: number;
  equity: { buyTotalReturn: number; spyTotalReturn: number; sharpe: number; maxDrawdown: number; months: number };
  informationCoefficient: number;
  topMinusBottom: number;
  deciles: number[];
  horizons: { label: string; buyHit: number; buyAlpha: number; restHit: number; restAlpha: number }[];
  regimes: { label: string; months: number; alpha: number | null }[];
  caveats: string[];
}

export const HISTORICAL_BACKTEST: BacktestSummary = {
  period: "Jan 2020 – Jun 2026",
  universe: 43,
  rebalances: 78,
  nameMonths: 2496,
  buyThreshold: 60,
  equity: { buyTotalReturn: 279.9, spyTotalReturn: 131.7, sharpe: 1.09, maxDrawdown: -29.9, months: 78 },
  informationCoefficient: 0.067,
  topMinusBottom: 4.1,
  deciles: [-0.9, -2.2, 1.3, 0.3, -0.6, 0.6, 1.1, 1.0, 1.6, 3.2],
  horizons: [
    { label: "1M", buyHit: 49, buyAlpha: 0.6, restHit: 46, restAlpha: -0.1 },
    { label: "3M", buyHit: 52, buyAlpha: 1.9, restHit: 46, restAlpha: -0.1 },
    { label: "6M", buyHit: 51, buyAlpha: 3.2, restHit: 44, restAlpha: 0.6 },
    { label: "12M", buyHit: 51, buyAlpha: 6.9, restHit: 44, restAlpha: 2.4 },
  ],
  regimes: [
    { label: "Expansion", months: 11, alpha: 0.9 },
    { label: "Reflation", months: 41, alpha: 0.9 },
    { label: "Stagflation", months: 26, alpha: 3.8 },
    { label: "Contraction", months: 0, alpha: null },
  ],
  caveats: [
    "Survivorship: universe is current large-caps that survived — absolute returns are optimistic; the relative BUY-vs-rest, IC and decile metrics are the robust evidence.",
    "No delisted names (FMP free tier omits them).",
    "As-of regime is a simplified FRED classifier and is descriptive only — it is not fed into the score.",
    "Sector valuation benchmarks held constant over time.",
    "In-sample risk: thresholds were hand-tuned — the live forward record is the un-backtested proof.",
  ],
};
