// Historical backtest summary — generated by research/backtest.mjs --full (point-in-time,
// free data: SEC EDGAR filing dates + Yahoo prices + FRED). 80 S&P 500 names with
// point-in-time membership. Committed as a static snapshot; re-run to refresh. The LIVE
// record (sl_track_summary) is separate and accumulates forward from the monthly cron.
//
// Honest read: on this broad, representative universe the edge is MODEST — the score≥60
// bucket beats "rest" at every horizon (the gap widens to ~4pp at 12M), but it only edges
// SPY (+162% vs +154%) and fine-grained decile ranking is roughly flat. A value/quality
// score underperforms a mega-cap-momentum tape (2020-24). A diverse curated set showed a
// larger edge (+210% vs +154%) — the truth is universe-dependent, which is exactly why the
// un-backtested live forward record is the real proof.

export interface BacktestSummary {
  period: string;
  universe: number;
  mode: string;
  rebalances: number;
  nameMonths: number;
  buyThreshold: number;
  equity: { buyTotalReturn: number; spyTotalReturn: number; sharpe: number; maxDrawdown: number; months: number };
  overlay: { buyTotalReturn: number; sharpe: number; maxDrawdown: number };
  informationCoefficient: number;
  topMinusBottom: number;
  deciles: number[];
  horizons: { label: string; buyHit: number; buyAlpha: number; restHit: number; restAlpha: number }[];
  regimes: { label: string; months: number; alpha: number | null }[];
  caveats: string[];
}

export const HISTORICAL_BACKTEST: BacktestSummary = {
  period: "Jan 2020 – Jun 2026",
  universe: 80,
  mode: "S&P 500 · point-in-time membership",
  rebalances: 78,
  nameMonths: 5941,
  buyThreshold: 60,
  equity: { buyTotalReturn: 162.4, spyTotalReturn: 154.2, sharpe: 0.86, maxDrawdown: -28.6, months: 78 },
  overlay: { buyTotalReturn: 178.4, sharpe: 0.99, maxDrawdown: -17.4 },
  informationCoefficient: 0.032,
  topMinusBottom: -0.7,
  deciles: [0.6, -2.2, -0.9, -2.0, -0.8, -0.1, -0.6, 0.2, 0.6, -0.1],
  horizons: [
    { label: "1M", buyHit: 49, buyAlpha: 0.1, restHit: 47, restAlpha: -0.3 },
    { label: "3M", buyHit: 47, buyAlpha: 0.2, restHit: 46, restAlpha: -0.8 },
    { label: "6M", buyHit: 48, buyAlpha: 0.7, restHit: 44, restAlpha: -1.6 },
    { label: "12M", buyHit: 47, buyAlpha: 1.3, restHit: 44, restAlpha: -2.9 },
  ],
  regimes: [
    { label: "Expansion", months: 11, alpha: 1.9 },
    { label: "Reflation", months: 41, alpha: 0.5 },
    { label: "Stagflation", months: 26, alpha: -0.7 },
    { label: "Contraction", months: 0, alpha: null },
  ],
  caveats: [
    "Modest edge: on this broad universe the score≥60 bucket only edges SPY (+162% vs +154%); the real, consistent signal is BUY-vs-rest (positive at every horizon, gap widening to ~4pp at 12M).",
    "Fine-grained ranking is weak here (decile spread ≈ flat) — a value/quality score lags a mega-cap-momentum market.",
    "Fully-delisted names omitted (Yahoo) → residual survivorship; add Tiingo for a fully bias-free universe.",
    "Macro overlay measured with the production regime engine (point-in-time FRED): it acts as a risk manager — cutting max drawdown ~40% (−28.6%→−17.4%) and lifting Sharpe (0.86→0.99), not adding raw stock-selection alpha.",
    "Fully-delisted names still omitted; sector benchmarks held constant; thresholds hand-tuned → the live forward record is the un-backtested proof.",
  ],
};
